version: '3'
services:
  prometheus:
    container_name: prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8000:8000
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=khaddemApp
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

volumes:
  db: