version: '3'
services:
  prometheus:
    container_name: prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

