version: '3'
services:
  prometheus:
    container_name: prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8000:8000

  db:
    image: mysql
    container_name: mysqldb
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    environment:
      - MYSQL_DB=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  adminer:
    image: adminer
    ports:
      - '8082:8080'
    restart: unless-stopped

volumes:
  db: