version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - '--config.file=./src/main/resources/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8000:8000
    depends_on:
      - prometheus