version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - prometheus