version: '3'
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090

  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8000:8000
    depends_on:
      - prometheus
      - mysqldb