version: '3'
services:
  prometheus:
    container_name: prometheus
    network_mode: bridge
    ports:
      - "9090:9090"
    image: prom/prometheus

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus

  spring-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: khaddem
    restart: "no"
    ports:
      - 8000:8000

volumes:
  db: